/*
 * Copyright (C) 2014 Andrew Comminos
 */

buildscript {
    repositories {
        maven { url "https://maven.google.com" }
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:7.4.2"
    }
}

allprojects {
    repositories {
        maven { url "https://maven.google.com" }
        mavenCentral()
    }
}

apply plugin: "com.android.application"

dependencies {
    implementation project(":libraries:Jumble")
  //  implementation fileTree(dir: "../libraries/Jumble", include: ["*.jar"])
    implementation "androidx.appcompat:appcompat:1.4.1"
    implementation "com.google.android.material:material:1.5.0"
    implementation "androidx.recyclerview:recyclerview:1.2.1"
    implementation "androidx.cardview:cardview:1.0.0"
    implementation "androidx.palette:palette:1.0.0"
    implementation "org.jsoup:jsoup:1.7.2"
    implementation "info.guardianproject.netcipher:netcipher:1.2"
}

android {
    namespace "com.morlunk.mumbleclient"
    compileSdkVersion 31
    buildToolsVersion "31.0.0"

    defaultConfig {
        applicationId "com.morlunk.mumbleclient"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 73
        versionName "3.3.0"
    }

    lintOptions {
        abortOnError false
    }
}
